export {default as NavBar} from './Navbar'
export {default as Button} from './button/Button'
export {default as Hero} from './Hero'
export {default as Accordion} from './Accordion/Accordion'
export {default as Tabs} from './Tabs/Tabs'
export {default as LoadingComponent} from './Loading/Loading'